const menu = {
  categories: [
    {
      id: "starters",
      name: "Starters",
      icon: "🥗",
      items: [
        {
          id: "s1",
          name: "Bruschetta",
          description: "Toasted bread with fresh tomatoes, basil, and garlic",
          price: 8.99,
          category: "starters",
          image: "bruschetta",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "s2",
          name: "Calamari",
          description: "Crispy fried squid with marinara sauce and lemon",
          price: 12.99,
          category: "starters",
          image: "calamari",
          tags: ["seafood"],
          popular: true,
        },
        {
          id: "s3",
          name: "Soup of the Day",
          description: "Chef's daily selection of seasonal soup",
          price: 7.99,
          category: "starters",
          image: "soup",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "s4",
          name: "Chicken Wings",
          description: "Crispy wings with buffalo sauce and blue cheese dip",
          price: 13.99,
          category: "starters",
          image: "wings",
          tags: ["spicy"],
          popular: true,
        },
      ],
    },
    {
      id: "mains",
      name: "Main Course",
      icon: "🍽️",
      items: [
        {
          id: "m1",
          name: "Grilled Salmon",
          description: "Atlantic salmon with lemon butter, asparagus, and wild rice",
          price: 26.99,
          category: "mains",
          image: "salmon",
          tags: ["seafood", "healthy"],
          popular: true,
        },
        {
          id: "m2",
          name: "Ribeye Steak",
          description: "12oz prime ribeye with garlic mashed potatoes and seasonal vegetables",
          price: 38.99,
          category: "mains",
          image: "steak",
          tags: ["beef"],
          popular: true,
        },
        {
          id: "m3",
          name: "Spicy Chicken Sandwich",
          description: "Crispy spiced chicken breast with jalapeños, slaw, and chipotle mayo",
          price: 16.99,
          category: "mains",
          image: "chicken_sandwich",
          tags: ["spicy", "chicken"],
          popular: true,
        },
        {
          id: "m4",
          name: "Mushroom Risotto",
          description: "Creamy arborio rice with wild mushrooms, truffle oil, and parmesan",
          price: 18.99,
          category: "mains",
          image: "risotto",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "m5",
          name: "Margherita Pizza",
          description: "Classic Neapolitan pizza with San Marzano tomatoes and fresh mozzarella",
          price: 17.99,
          category: "mains",
          image: "pizza",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "m6",
          name: "Beef Tacos",
          description: "Three tacos with seasoned ground beef, pico de gallo, and guacamole",
          price: 14.99,
          category: "mains",
          image: "tacos",
          tags: ["beef", "spicy"],
          popular: false,
        },
      ],
    },
    {
      id: "sides",
      name: "Sides",
      icon: "🍟",
      items: [
        {
          id: "si1",
          name: "French Fries",
          description: "Crispy golden fries with sea salt",
          price: 4.99,
          category: "sides",
          image: "fries",
          tags: ["vegetarian"],
          popular: true,
        },
        {
          id: "si2",
          name: "Onion Rings",
          description: "Beer-battered onion rings with ranch dipping sauce",
          price: 5.99,
          category: "sides",
          image: "onion_rings",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "si3",
          name: "Side Salad",
          description: "Mixed greens with cucumber, cherry tomatoes, and vinaigrette",
          price: 5.99,
          category: "sides",
          image: "salad",
          tags: ["vegetarian", "healthy"],
          popular: false,
        },
        {
          id: "si4",
          name: "Garlic Bread",
          description: "Toasted sourdough with herb garlic butter",
          price: 3.99,
          category: "sides",
          image: "garlic_bread",
          tags: ["vegetarian"],
          popular: false,
        },
      ],
    },
    {
      id: "drinks",
      name: "Drinks",
      icon: "🥤",
      items: [
        {
          id: "d1",
          name: "Craft Lemonade",
          description: "Fresh-squeezed lemonade with mint and basil",
          price: 4.99,
          category: "drinks",
          image: "lemonade",
          tags: ["non-alcoholic"],
          popular: false,
        },
        {
          id: "d2",
          name: "Sparkling Water",
          description: "Premium sparkling mineral water",
          price: 2.99,
          category: "drinks",
          image: "water",
          tags: ["non-alcoholic"],
          popular: false,
        },
        {
          id: "d3",
          name: "House Red Wine",
          description: "Full-bodied Cabernet Sauvignon by the glass",
          price: 9.99,
          category: "drinks",
          image: "wine",
          tags: ["alcoholic"],
          popular: false,
        },
        {
          id: "d4",
          name: "Craft Beer",
          description: "Rotating selection of local craft beers",
          price: 7.99,
          category: "drinks",
          image: "beer",
          tags: ["alcoholic"],
          popular: false,
        },
        {
          id: "d5",
          name: "Iced Coffee",
          description: "Cold brew with choice of milk and syrup",
          price: 5.99,
          category: "drinks",
          image: "coffee",
          tags: ["non-alcoholic"],
          popular: true,
        },
      ],
    },
    {
      id: "desserts",
      name: "Desserts",
      icon: "🍰",
      items: [
        {
          id: "de1",
          name: "Chocolate Lava Cake",
          description: "Warm dark chocolate cake with vanilla ice cream",
          price: 9.99,
          category: "desserts",
          image: "lava_cake",
          tags: ["vegetarian"],
          popular: true,
        },
        {
          id: "de2",
          name: "Crème Brûlée",
          description: "Classic French custard with caramelized sugar crust",
          price: 8.99,
          category: "desserts",
          image: "creme_brulee",
          tags: ["vegetarian"],
          popular: false,
        },
        {
          id: "de3",
          name: "Tiramisu",
          description: "Traditional Italian tiramisu with espresso and mascarpone",
          price: 8.99,
          category: "desserts",
          image: "tiramisu",
          tags: ["vegetarian"],
          popular: false,
        },
      ],
    },
  ],
};

const allItems = menu.categories.flatMap((c) => c.items);

function getItemById(id) {
  return allItems.find((item) => item.id === id);
}

function findItemsByName(query) {
  const q = query.toLowerCase();
  return allItems.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.tags.some((t) => t.toLowerCase().includes(q))
  );
}

module.exports = { menu, allItems, getItemById, findItemsByName };
